coolstation/coolstation

config/motd.txt
config/rules.html

just some little motd cleanup and practice

---

code/obj/item/fitness.dm

Adds the ability to give someone the ol' prickly punching bag!
Also adds the ability to remove/reset the ol' prickly punching bag with a pair of wirecutters.
I even kinda lazily tested it, too!
'cause it'll be funny. At least for a bit.
```changelog
(u)Tamber
(+)Add the option to boobytrap a punching bag with a syringe. And also to be able to remove the syringe.
```

Exercise is boring. Let's add a little spice! (But probably Krokodil)

---

code/modules/vending/vending.dm

FREE CHOKLIT BAR! JUST REACH UP IN THERE AND TAKE IT!
F R E E   C H O K L I T !
```changelog
(u)Tamber
(*)You can now climb into -- or shove others into -- vending machines.
(+)Sometimes you can get free item.
```

Gonna stick my arm up in the vending machine for a FREE CHOKLIT BAR!

---

_std/__build.dm
_std/__std.dme
_std/chat.dm
_std/macros/strings.dm
code/__secret_public.dme
code/datums/antag_weighting.dm
code/datums/api_handler.dm
code/datums/components/barber.dm
code/datums/configuration.dm
code/datums/savefile.dm
code/modules/admin/admin.dm
code/modules/admin/admin_verbs.dm
code/modules/admin/bans.dm
code/modules/admin/playernotes.dm
code/modules/sound/playsound.dm
code/player.dm
code/procs/export_data.dm
code/procs/helpers.dm
code/world.dm
coolstation.dme

idk, i'd like to play eventually 
```changelog
(u)warc
(*)refactor for Opengoon API ```

OPENGOON-COMPAT

---

maps/cogmap2.dmm

there's no label setup here is there
On cogmap 2, moves Morty from the chaplain's office to his rightful throne in the morgue.
Also I replaced two unrecognised map chunks in the editor blindly with what I'm pretty confident is blank space. I have no idea what they used to be but on a visual inspection I couldn't find holes in the station so it's probably fine. Map opens in strongdmm again though!
Medbay deserves their obstructing friend. :)

He's back with a vengeance

---

code/modules/power/cable.dm

do you believe this
will you LOOK at THAT
just call me mister butterfingers
added an old, non-compiling cable.dm when sorting out my messy repo business
is my face red
```changelog
(u)ReginaldHJ
(+)conduits: now with added "it can actually compile now"!
```

Conduits - wow that was an old cable.dm how on earth did that happen

---

code/mob.dm
code/modules/power/lighting.dm
code/modules/robotics/bot/mulebot.dm
code/obj/stool.dm

early part of ceiling interaction. now you can stand on a stepladder and interact with the ceiling.
gotta be able to interact with the things on the ceiling.
stepladder works. chair will work as expected once look-up toggle is in. mule is being worked on.
```changelog
(u)ReginaldHJ
(*)Now you can replace bulbs in the ceiling fixtures.
```

okay now you can stand on some things and touch stuff on the ceiling

---

maps/cogmap.dmm
maps/donut3.dmm

Cogmap 1 fails to compile because of a mystery undefined symbol, I replaced that symbol with a space tile (it's probably fiiiine)
Donut 3 fails to compile because it doesn't know what a cake icing tube is so I just removed them (we'll probably have other maps instead anyway)
Make sure CI checks are passed cleanly, light it up green. Should not actually impact other code or gameplay

Minor map alterations over compile issues

---

code/modules/chemistry/tools/food_and_drink.dm

There was a problem in the interaction between a player and drinking glasses when they have enough urine, resulting in unwanted or unexpected behavior
TODO: investigate balloons and beakers for similar user experience issues
It's not
```changelog
(u)ReginaldHJ
(+)Fixed a bug involving living players and player corpses able to infinitely piss in drinking glasses.
```

infinite corpse piss glass bug fixed

---

maps/cogmap.dmm
maps/donut3.dmm

oops, forgot to push the fix up, there were another couple undefined symbols that i replaced with space
clearing CI errors until we have a more focused and homegrown maplist

Cogmap 1 corruption fix

---

code/mob.dm
code/mob/dead/observer.dm
code/modules/antagonists/changeling/abilities/transform.dm
code/modules/chemistry/Reagents-Medical.dm
code/modules/chemistry/Reagents-PoisonEtc.dm

Face unmelting via synthflesh.
i ported face unmelting what more could you want from life
face melting has no fix. thats a problem. Also ghosts are called unknown and thats annoying as fuck so i unfucked it.
synthflesh fixes melted faces now

Face unmelting

---

code/mob/living/life/sight.dm
code/obj/item/cable_coil.dm

-Fix cable coil cutting crashing if you put in nonsense to cancel
-Fixes the butt-ugly borg meson overlay by making it respect widescreen prefs (which is everyone anyway)
I did a bad coding and also why the fuck have borg mesons been broken for 2 years over this trivial a thing

Bugfixes (cable coils, borg mesons)

---

assets/maps/random_rooms/3x5/buttstore.dmm

added a new random room
it's not

the butt store called

---

code/datums/mutantraces.dm

Monkeys had their head too far up by 2px, now it's fine

fix monkey heads

---

code/credits.dm
coolstation.dme
interface/skin.dmf

As title, this makes a button for a credits/attribution tab, all based on hotkeys.dm. The actual window sucks but I don't really touch HTML normally, so I have very little idea what I'm doing or where most of these dang assets even came from yonks ago.
It'd be nice, right?

Adds a mostly placeholder credits tab

---

code/WorkInProgress/HaineWhatever.dm
code/datums/components/barber.dm
code/datums/gamemodes/gm_parent.dm
code/datums/limb.dm
code/mob/living/carbon/human/monkeys.dm
code/mob/living/critter/aquatic.dm
code/modules/admin/randomverbs.dm
code/obj/item/cameras.dm
code/obj/item/device/voltron.dm
code/obj/item/gift.dm
code/obj/item/grab.dm
code/obj/item/implant.dm
code/obj/item/misc_weapons.dm
code/obj/item/mob_parts/human_parts.dm
code/obj/item/uplinks.dm
code/obj/machinery/singularity.dm
code/obj/misc_junk.dm
code/obj/portal.dm
code/obj/stool.dm
code/procs/mob_procs.dm

Makes whatever I could find with VSC searches respect pronouns if possible. I don't think blobs have pronouns so they're SOL. Also the only search that got me much was `their [` so I'm expecting this to be close to all of it.
Adds the proc `pluralize_or_not` which is intended to let you sort out "she has/they have" grammar stuff.
I've made sure the thing compiles but I haven't tested if all the grammar looks correct because the changes are all over the place.
I require my pronouns be respected when someone mauls me with bear arms. :P

pronoun replacements

---

code/atom.dm
code/atom/UpdateOverlays.dm
code/datums/tooltip.dm
code/mob/living/critter/flock/flockdrone.dm
code/mob/living/critter/flockcritter_parent.dm
code/mob/living/critter/small_animal.dm
code/modules/admin/atom_verbs.dm
code/modules/chemistry/Reagents-Base.dm
code/modules/chemistry/Reagents-FoodDrink.dm
code/modules/chemistry/Reagents-Misc.dm
code/modules/events/supply_drop.dm
code/modules/food_and_drink/snacks.dm
code/modules/items/gimmick/figurine.dm
code/modules/materials/Mat_ProcsDefines.dm
code/modules/medical/genetics/bioEffects/powers.dm
code/modules/mining/ore.dm
code/modules/power/cable.dm
code/obj/flock/furniture.dm
code/obj/item/handcuffs.dm
code/obj/item/material.dm
code/obj/table.dm
code/obj/window.dm
code/turf/floors.dm
code/turf/floors_airless.dm
code/turf/floors_unsimulated.dm
code/turf/turf_autoalign.dm
code/turf/turf_flock.dm
code/turf/walls.dm

Ports https://github.com/goonstation/goonstation/pull/10807 more or less
A couple things they have we don't, and I think I've been a little more thorough with the turf part than Ze was.
Not copying mats on turfs saves a ton of time roundstart, holy shit
Doesn't seem to help much with explosions yet but I need to have dinner now so bye

Ports 10807

---

code/obj/vehicle.dm

return of hellshoe

---

code/datums/manufacturing.dm
code/obj/item/clothing/helmets.dm
code/obj/item/clothing/suits.dm
code/obj/machinery/manufacturer.dm

Adds Industrial Combat Armor to the mining fab. It costs alot compared to it's sibling, and probably can be tweaked more depending. Also gives the indy helmet a minor nerf in melee protection. It's kinda tested but needs more input than just me. 
Hey this is lyin around in the code with no way to produce it. who knows maybe I'll actually finish a PR for this game for once.
```changelog
(u)Eagle
(*)Industrial Combat Armor has made it to the mining. Finally now you too can be unstoppable*!
(+)Indy helmets have received a small nerf to overall durability
```

Industrial Combat Armor

---

code/obj/machinery/phone.dm

Put the while loop in `draw_cord` into a `SPAWN_DBG` because otherwise it holds up the proc above it and the phonebook UI never opens. Also it never stops the phone from ringing.
Fixes #224 and fixes #225

Fix phonebook not opening 

---

_std/plane.dm
code/mob.dm

Cherry pick fix
this man ate my son

Fix plane runtime on game close

---

maps/config/standard.dm

Switch the fallback map to chunk instead of cog2
Cog2 doesn't compile and we chunk

Change default map to chunk

---

code/modules/food_and_drink/snacks.dm

Undos donk nerf. You can shock your donks again. Also ups the omnizine dose because im pretty sure that was nerfed too. 
You gotta put a banging donk on it.
There can be some improvements (Scalding being enabled for extremely high temps, Fiddling with heat lenghts for using the microwave or using other sources) but donks are a nice source of off the grid healing.
```changelog
(u)Eagle
(+)Donk nerf reverted. Donk Responsibly.
```

shockurdonks

---

code/datums/broadcasts.dm

Adds a Tv broadcast I wrote while working on some other things and being unable to sleep
hank i know i can say penis please let me watch something else
```changelog
(U) Eagle
(+)Added a new TV program
```

New TV broadcast

---

_std/defines/temperatures.dm
code/area.dm
code/modules/chemistry/tools/dispensers.dm
code/modules/chemistry/tools/food_and_drink.dm
code/turf/turf.dm

Ants hopefully cannot spawn in the extreme cold or heat
ants in frieser is bad

try these ants for a size

---

code/mob/melee_attack_procs.dm
code/obj/item.dm

Helps prevent having a stock of brute patches just making you unkillable, and causes reasonable consequences for having the shit beaten out of you all round.
```changelog
(u)awfulworldkid
(*)Head injuries from weapon crits or strong punches now cause brain damage
```

Make head injuries cause brain damage

---

code/WorkInProgress/Azungarstuff.dm
code/datums/jobs.dm
code/obj/item/storage/ammo_pouches.dm
code/obj/item/storage/backpack_belt_etc.dm

no more SECURITY POUCH!
no more SECURITY BELT!  
security officer must now deal with ~standard inventory size~ like da rest of da crew
ALSO!!!!  a mere single handcuff, a trifle......
to compensate?  handcuff dispenser turned into zipties: they suck but you get lots

kick security in face 9 times

---

code/obj/machinery/door/airlock.dm
code/obj/machinery/door/door_parent.dm

doors autoclose properly
doors autoclose properly
```changelog
(u)jimmyl
(+)doors autoclose properly
```

doors autoclose properly

---

code/modules/atmospherics/machinery/mixer.dm
code/obj/machinery/computer/general_air_control.dm

gas mixer ui updates when you click the buttons
responsive is good
```changelog
(u)jimmyl
(+)gas mixer ui updates when you click the buttons
```

gas mixer ui updates when you click the buttons

---

assets/maps/random_ships/30x25/hull_escape_crash.dmm
assets/maps/random_ships/30x25/hull_tow_truck.dmm

Adds two more annoying/hazardous scrapper prefabs. Maps here: https://discord.com/channels/880554731452383312/954457688190910544/1330594096808726578
Wanted to try weirder kinds of scrapping
```changelog
(u)Krowmeat
(*)Added two new scrapyard ships you might run across
```

Scrapping ships

---

buildByond.conf
tools/bootstrap/python
tools/bootstrap/python.bat
tools/bootstrap/python36._pth
tools/bootstrap/python_.ps1

updates bootstrap from goonstation with all changes up to Oct 8, 2023
also bumps the python version of the project up to 3.8.0 so mapmerge works better or something
works i think
mapmerge2
not really player facing???

updates bootstrap from goonstation

---

code/WorkInProgress/simroom.dm
code/datums/embedded_controller.dm
code/modules/economy/stocks/stock_machine.dm
code/modules/power/TEG.dm
code/modules/power/turbine.dm
code/obj/machinery/computer/QM_order.dm
code/obj/machinery/computer/door_control.dm
code/obj/machinery/computer/general_air_control.dm
code/obj/machinery/computer/pod.dm
code/obj/machinery/computer/robotics.dm
code/obj/mining.dm

changes all window=computer to window=computer_\ref[src]
fixes the close button disappearing whenever CHUI is involved
```changelog
(u)jimmyl
(+)fixed pump control computers close buttons just disappearing
```

changes windows id of many computers

---

maps/klushywip/bayoubend.dmm

adds a loafer to bayou bend that has been damaged by prior use
the loafer is cool and has some cool stuff that you cant get anywhere else
```changelog
(u)jimmyl
(+)bayou bend gets a loafer in security maintenance
```

adds loafer to bayou bend

---

code/mob.dm
code/mob/living.dm
code/procs/mobprocs/chatprocs.dm

(probably) fixes stuck typing indicator (if you type via the input popup)
i cant reproduce it so it probably works???
https://github.com/user-attachments/assets/741f1c85-d0c8-446f-8a51-4c2bb9c402b9
bug bad
```changelog
(u)jimmyl
(+)fixes stuck typing indicator probably
```

(probably) fixes stuck typing indicator

---

maps/klushywip/bayoubend.dmm

missing
```changelog
(u)jimmyl
(+)added the pda cartridge vendor and mainframe radio to bayou bend
```

adds the pda cartridge vendor and mainframe radio to bayou bend

---

code/WorkInProgress/MechanicMC14500.dm

Ports my control unit refactor from goon
https://github.com/goonstation/goonstation/pull/21956
Makes it run at a consistent speed instead of in absurd bursts, so original PR for technical details
There is no reason to output five signals 0.1s apart and then halt for two odd seconds
```changelog
(u)patricia
(+)Control units now output signals and execute programs at a more consistent rate
```

Refactor control unit execution process 

---

code/WorkInProgress/bowling.dm
code/datums/controllers/process/forcedMovement.dm
code/mob/living/carbon.dm
code/modules/fluids/fluid_core.dm
code/obj/decal.dm
code/obj/decal/cleanable.dm
code/obj/item/clown_items.dm
code/obj/item/device/pda2/pda2.dm
code/procs/mob_procs.dm

Adds last gasps to lube and banana peels and whatever other slips I could find
Falling over should interrupt your speech

Adds lastgasp() to various slips

---

code/mob/input.dm
code/modules/interface/mob_input.dm

Reverts coolstation/coolstation#358

yeah yknow what fuck this

---

code/mob/new_player.dm
code/modules/admin/admin_verbs.dm

Respawn as Job admin verb no longer sends you to the latejoin spawn or turns you into a football player
More good better

Respawn as Job respawns you in place

---

code/datums/jobs.dm

Added every scrub option to the jumpsuit list which is treated as a weighted list, but I don't think they should be weighted so all the weights are one. Also gives them a medical headset.
Nurses should have diverse scrubs and access to the medical channel

Nurses spawn with random scrubs and a medical headset

---

code/mob/living.dm

AIs can now use their secure channels when deployed to eyebots and shells
Can't do your dang job without em'

AI eyebot can use secure radio!

---

browserassets/css/chui/themes/default/default.css

… scrollbar
More work on new theme

Restyle the window decorations on chui windows

---

code/datums/preferences.dm

Job panel looked bad
Now it looks pretty stylin
Missed it on the first pass

tweak job panel for new chui theme

---

code/datums/datumvars.dm
code/modules/admin/player_panel.dm

Some admin stuff needed adjustments for the new chui theme
Looked bad

Style player options and view variables

---

browserassets/css/chui/themes/default/default.css

fix the default.css css file

---

code/datums/components/hallucinations.dm

Hallucinations were losing variable data when checking for dupes! This fixes that.
Fix!

Fix hallucinations nulling vars on dupe

---

code/obj/machinery/shitty_grill.dm

Fixes a bit of inaccessible code in the shitty grill that lets you know when you've burned your steak by replacing < with <=
bugfix

fixes minor bug in shitty_grill

---

browserassets/css/chui/themes/default/default.css
code/chui/theme.dm
code/mob/new_player.dm

Reverts coolstation/coolstation#516 - broke chui

Revert "Native scrollbars and minor margin tweak"

---

code/datums/components/pitfall.dm
code/modules/admin/admin_verbs.dm
code/modules/admin/debug.dm

Devtools for webview that let coders give anyone a webview inspect button temporarily.
Needed to debug Cam's client

bugfixes and webview devtool granting

---

code/chui/pcui/templates/selector-template.dm

Pressing cancel won't activate the selected location and will instead just close the window
Cancel is not supposed to do that

Cancel button dosen't activate jump form

---

_std/__build.dm
browserassets/Gruntfile.js
browserassets/js/browserOutput.js
browserassets/js/chui/chui.js
browserassets/tgui/tgui.html
config/config.txt

WebView2 prefers having the CDN on HTTPS, possible fix for Linux users.
Linux users should be able to play without obnoxious UI issues.

Moves CDN to HTTPS

---

config/config.txt

Accidentally turned off the CDN for an hour, now it's back on.
Had to turn it off for TGUI testing, accidentally pushed that shit.

fuckin OOPS

---

code/mob/living.dm
code/mob/living/carbon/human.dm

Let critters slidekick, doesn't seem bad for balance they can't push people because they're intangible 
I think it's really funny
https://github.com/user-attachments/assets/ddc17195-fa69-42eb-b541-84b31ed38499

Allow critters to slidekick

---

code/modules/chemistry/Chemistry-Holder.dm
code/modules/chemistry/Chemistry-Reagents.dm
code/modules/chemistry/Reagents-Base.dm
code/modules/chemistry/Reagents-ExplosiveFire.dm
code/modules/chemistry/Reagents-FoodDrink.dm
code/modules/chemistry/Reagents-Medical.dm
code/modules/chemistry/Reagents-Misc.dm
code/procs/fireflash.dm

After using the previous iteration to test on live with some engineers, replaces it with proper chemical energy. Values are calculated from real world where possible, based on an assumption that a 400 unit fuel tank == a 10 liter jerrycan. This one works so much better.
That previous iteration sucked.

Second iteration of chemical combustion heating atmos

---

code/mob/living/carbon/human/virtual.dm

ghosts if real body gibbed in vr
more ghosts!
#264

fix vr nullspace

---

code/datums/traits.dm

Adds milk to the list of things people can be allergic to when they pick the trait.
Because its funny.

Adds milk to the allergy trait allergen list

---

code/datums/controllers/job_controls.dm

Custom job maker was spawning people in naked, due to incorrect formatting of equipment.
Admin tool wasn't useable.

Fixes up the custom job maker

---

code/mob/living/carbon/human/virtual.dm

Reverts coolstation/coolstation#558
This messed up the vr, sorry

Revert "fix vr nullspace"

---

code/WorkInProgress/ItemSpecials.dm
code/global.dm
code/mob/input.dm
code/modules/admin/admin.dm
code/procs/gamehelpers.dm

Ports with full permission (he told me about it and asked if i wanted it) WYSIWYG by TDHooligan.
This makes attacking someone moving away from you FAR more reliable, significantly reducing the jank of "guy moves in, hits you while moving, darts back and can't be hit while moving".
See [#21804](https://github.com/goonstation/goonstation/pull/21804) on Goonstation for more details.
EN PASSANT COMBAT
EN PASSANT COMBAT
EN PASSANT COMBAT
```changelog
(u)TDHooligan
(*)Melee attack range checks have been adjusted, you can now more reliably hit players as they are moving away from you.
```

WYSIWYG by TDHooligan!

---

code/client.dm
code/modules/gunse/modular_guns.dm
code/modules/recoil/recoil_controller.dm
code/obj/item/gun/gun_parent.dm
code/procs/helpers.dm
coolstation.dme
interface/skin.dmf

it my recoil from Goonstation, at https://github.com/goonstation/goonstation/pull/18161 
working for modular gunse. icon recoil disabled for them though as it broken.
fixed some bugs gunse introduces
contains:
Camera recoil
Recoil-induced inaccuracy (capped at 0 for gunse)
Icon tilting (disabled for gunse. breaks with how theyre rendered)
recoil!
someone suggested nabbing it
```changelog
(u)TDHooligan
(*)Gunse now kick your screen about. disable it under Game->Effects->Camera Recoil
```

adds recoil
