- code/WorkInProgress/recycling/crusher.dm
```changelog
(u)ReginaldHJ
(+)The crusher hungers and will not wait.
```
> Return of Old Crusher

- code/global.dm
- code/modules/admin/admin.dm
- code/modules/admin/admin_verbs.dm
- code/modules/admin/toggles.dm
- code/procs/mobprocs/chatprocs.dm
Sounds that come from emotes and have pitch affected by age do not have any variation like they used to. This changes that to add a slight random chance of pitch changes, centered around the emoter's age.
nothing more boring than a bunch of 30 year old spacepersons farting at the same pitch forever
```changelog
(u)ReginaldHJ
(*)Now instead of age being your sole determinator of emote sounds (farts, screams) there's a slight variation! Admins can turn this on and off globally.
(+)Eventually they'll be able to do it on an individual basis.
```
> slight randomization of emote sound pitches (w/ admin toggle)

- code/obj/item/table_rack_parts.dm
- code/obj/stool.dm
Stepladders, specialized use for working with ceiling mounted lighting fixtures and other machinery-to-come.
This is a ladder that doesn't transport you from one location or z-level to another... it takes you between!
Sprites, ceilingvision, "reach ceiling" handling, and wrestling gimmick to follow.
It's a quick and dirty add, will be tweaked and updated soon.
I will be adding ceiling mounted lights that are invisible except when you're "looking" at them. We might also put some atmos pipes or disposals or wiring up there so it compliments the underplating crawlspace nicely.
It's good to have a vision transition so you can actually change the bulbs and work with them, and a stepladder seemed appropriate. (Standing on chairs will also do this but it will be a specific, manual toggle there) …
> initial creation of stepladders

- code/modules/power/lighting.dm
This PR adds ceiling lights!
they're basically reused floor lights with transparency, set above the player plane
in the end, they won't be seen unless you are specifically looking up at them (invisibility/plane overhaul is coming later)
Future behavior will have them invisible and un-interact-able by default.
You will need to see them (some kinda look-up toggle command!) and also have your player mob be high enough, i.e. standing on a chair or stepladder or MULE. in the future, perhaps even a forklift or drivable scissor lift, for additional OSHA-violating ceiling-wiring fun.
Getting good lighting is a bit of a challenge and potential clutter point, especially when doors or perspective walls throw off the alignment.
Having decent ceiling lights tucked up and away makes it easier for …
> Initial release of ceiling lights

- code/procs/export_data.dm
changes stat reporting
the server will not attempt to send round start or end data to the hub when the configured environment is dev
no big deal when running the server in dream daemon but its annoying when trying to debug from vscode
> no hub round data in dev

- code/mob/living/silicon/drone.dm
- code/modules/power/cable.dm
- code/obj/item/cable_coil.dm
- code/turf/floors.dm
This PR is a bit of scattershot of code cleanup regarding cable coils, largely because if you look at cable coil code long enough you get annoyed at all the bullshit it's reinventing. I didn't even do the thing I started looking at the code for.
-Making a new cable object is now its own little proc to save copy-paste.
-The four(!) procs for putting a cable on the floor have been merged into two (one targeting turfs and one other placed cables), which had considerable overlap anyway. Most of the output messages got axed in the process . I'm thinking if those have to stay around it's probably best to do something with return codes, since putting them directly in the procs can get spammy when autolaying.
-As a by-effect of the above, auto-laying cable can now also shock you if. The fact that …
> Cables but without ruining the history this time?

- code/modules/admin/diagnostics.dm
- strings/admin_changelog.txt
Ports (read: copy-pastes with one small string change) my light switch debug overlay from goon
Green areas have at least one light switch, mouse hover and the lower left of an area lists the amount
Red areas have none
White turfs have a light switch object on them
I didn't really bother checking for a set-up `otherarea` var for simplicity's sake so if you're toying with that, god help you.
It's intended as a mapping tool because having the switches everywhere is good but they're easy to overlook.
(I saw the mail routing PR and thought "oh hey mapping QOL I have one of those")
Admin changelog included
> Goshhecking light switches debug overlay

- code/obj/machinery/dispenser.dm
[feat]
Enables tank storage units (the ox/plasma dispensers) to store tanks from crewmembers (up to the default 10 total for both), which I'm sure just means people returning their used tanks for recycling with no crime happening whatsoever.
I've wanted it to be possible for crimespeople to sabotage these things with doctored tanks since forever.
```changelog
(u)BatElite
(+)You can now re-insert oxygen/plasma tanks into the storage units.
```
> Allow for tank storage crime

- code/obj/machinery/door/airlock.dm
- maps/cogmap.dmm
This PR removes any remaining airlock access things I could find, so that any door defaults to no requirement.
Also updates cog1 to fix the doors that were still on the old system. I must have gotten most of them at least. Other maps may or may not have broke. In particular every listening post is probably freely accessible now because they're mostly copy-pastes of a years old design.
Making everything consistently require access spawners be placed is more sensible than having two systems run parallel to one another.
Probably none necessary, even though it will break some shit I'm guessing we get the maps patched up before launch
> Remove straggler access defines on airlocks

- browserassets/html/admin/berate_heavy.html
- browserassets/html/admin/berate_light.html
- code/modules/admin/admin.dm
- code/modules/admin/admin_verbs.dm
- code/modules/admin/player_panel.dm
Adds a thing to player options for admins to tell someone off for their gimmick. They come in two flavours, one for the case where they have an alright idea except we've had this exact same shit 12 times in the last 2 days. The other is for when it's just horseshit.
Berate Gimmick option in the Player Options:
Prompt:
Mild:
Severe:
Sometimes you just need someone to fuck off with that shit
(Warc mentioned something like this last night (in fact I copied the wording) and it turned out pretty easy to do)
N/A
> Adds admin button to tell off people for their gimmick

- code/WorkInProgress/hotkeys.dm
- code/mob/living.dm
As title, you can stop pulling shit with ctrl-click now.
I made this for goon where the eyebots can now pull shit but don't have a good way to release pulls, but it's good QOL in general.
```changelog
(u)BatElite
(+)The CTRL-click shortcut can now also be used to stop pulling things
```
> CTRL-click allows releasing pulls

- code/datums/jobs.dm
- code/datums/supply_packs.dm
- code/obj/item/clothing/armor.dm
- code/obj/item/device/pda2/pda2.dm
- code/obj/storage/secure_closets.dm
-secoffs spawn without armour vests (there's still 3-5 lockers on each map they'll be fine)
-secoffs spawn without implants but the HoS still gets the anti-mindslave
-armour vests are the grey type by default (except the bartender's is the "light" black type)
-removes now useless vendor tokens from armoury closet and that one cargo crate. The latter is also bumped down in price because 10k for a vest/helmet/cuffs is steep
-Gives both flavours of vice officer assistant sec belts instead of vendor tokens. Don't think they need to be tasing the stoners.
-sec PDAs don't have the alerter, HoS PDA still does (but maybe I should remove that too?)
Things that this PR just kinda leaves hanging:
-sec PDAs are still in all the health alert groups but I don't understand how those groups work, so I …
> Mall cop-ification part 2

- code/modules/hydroponics/plant_mutations.dm
un nerfs quivering contusine
curare is fun and flirty
reverted quivering contusine nerf such that it produces curare instead of histamine again
```changelog
(u)Gibletfeets
(+)un nerfed quivering contusine
```
> making quivering contusine cool

- code/datums/disease.dm
- code/modules/medical/diseases/dna_spread.dm
Modernises Space Rhinovirus, the disease that turns patients into copies of patient zero (until cured), to current systems and code.
-Removes unused disease_data from disease datums, moves strain_data from /datum/ailment to datum/ailment_data/disease
-Fixes diseases not propagating their method of spreading (at the moment this has no round effect since AFAICT no contagious diseases occur normally)
-Makes Space Rhinovirus work again, since it was both unticked and referenced ancient-ass mob systems that I've never even experienced.
It's all one commit because I copy-pasted my work from Harmony. :P 
**Requires cherry-picking https://github.com/goonstation/goonstation/commit/ec405971901fb320c95120d540bd00769fc2bf90 to work, which is what I get for copy-pasting I guess.**
Sounds like a fun …
> Modernizes Space Rhinovirus

- code/datums/emotes/emote_complex.dm
- code/datums/pronouns.dm
fixes dying humans not doing a deathgasp ('cause death() sets dead before calling emote())
fixes a case in it/its pronouns, hopefully it's good now grammar is fucking hard
closes #105 
deathgasp not working just isn't acceptable.
> deathgasp, it/its fixes

- code/datums/controllers/event_controls.dm
- code/datums/controllers/process/random_events.dm
[feat]
Stealing a good idea from somewhere in TG-styled code (IDK what monke is based on or where the feature originates), this PR implements advance admin warning for random events. You can cancel an upcoming event or change what it's going to do, so you can have the game _not_ do a rad blowout a minute before the shuttle docks or turn every major event into a blowout if you so wanted.
Also messes a little with the game panel and defines.
-Major events can have 2 warning times defined (to account for chat scroll), minor and spawn events have 1.
-Events are now picked at the time that the warning happens instead of when the event timer rolls over.
-The start times for each event cycle have been moved to defines, and instead sets the time the initial events are scheduled to those times …
> Admin warnings/controls for upcoming random events

- _std/__build.dm
- _std/defines/item.dm
- _std/macros/mob_properties.dm
- code/WorkInProgress/AnimationLibrary.dm
- code/WorkInProgress/recycling/conveyor.dm
- code/datums/controllers/action_controls.dm
- code/mob.dm
- code/mob/dead.dm
- code/mob/living.dm
- code/mob/living/carbon/human.dm
- code/mob/living/intangible.dm
- code/modules/fluids/fluid_turf.dm
- code/modules/status_system/statusEffects.dm
- code/obj/item/material.dm
- code/obj/item/tank.dm
- code/turf/turf.dm
- maps/oshan.dmm
[feat]
Ports 8766 from goon (PROP_ATOM_FLOATING for conveyor belts) as a prerequisite for swimming. Sets the current map to Oshan so we can all have a nice swim around.
This PR implements swimming as a verb on mob/living, along with swim-up/swim-down for ocean maps. Jetpacks can serve much the same purpose, but don't have restrictions on holding things that are too heavy
Swimming is possible in sufficiently flooded rooms or the ocean, and will automatically be attempted if you go over a trench hole. swimming up and down lets you go into and out of the trench.
Aside from trench maneuvreability, swimming lets you:
-go over glass shards with impunity
-be unaffected by conveyors (this is what 8766 did mostly)
I should probably add crossing railings to that list but I didn't
Misc changes:
-You …
> Ports swimming

- code/modules/chemistry/tools/dispensers.dm
- code/modules/power/lighting.dm
- code/modules/transport/pods/ships.dm
- code/obj/bookcase.dm
- code/obj/displaycase.dm
- code/obj/item/rcd.dm
- code/obj/railing.dm
- code/obj/table.dm
- code/turf/walls.dm
Adds chat groupings to the following (1 group per entry, might have been a little aggressive grouping some of these things):
-moving over railings
-using tools on railings
-(un)fastening watercoolers
-(dis)connecting watercooler bottles
-taking watercooler cups
-unscrewing light fixtures
-RCD switching modes
-RCD start construction notice
-RCD ammo tally post-construction
-vehicle frame deconstruction
-vehicle frame construction
-bookcase disassembly
-antique laser crafting steps
-making reinforced wood tables
RCDs:
-Merged messages for topping up an RCD and partially refilling one (the former was superfluous since both woudl trigger, but I think "units of matter" is less awkward than "matter-units" :V)
-Added a workaround for the damned "uselessly hits wall" messages for RCDs so that …
> Add message groups to a bunch of things

- _std/mapDefines.dm
- code/mob/dead/ai-camera.dm
- code/mob/living/silicon/ai.dm
- code/mob/living/silicon/ai/camera_handling.dm
- code/z_adventurezones/lavamoon.dm
[feat]
Makes AI more functional when they need to also go on Z3
-AI eye can go around on Z3 fine & track people on both levels (but with 1 client I can't test the latter well)
-AI eye can click ladders to climb them, but this turns out to be largely useless since most are out of camera cover. Gonna need some dedicated buttons for on the HUD I think.
-Camera visibility calcs also run on Z3 if necessary. Entering/leaving AI eye is pretty laggy though, ~25k high priority static overlays take a bit of a toll (for comparison, cog1 has ~14k)
Currently implemented mostly via a define that adds some exceptions for Z3. I'd love for some kind of arbitrary "these z levels are considered station" list per map to sate my kink for making everything generalised beyond what it'll ever need to support, …
> Add AI support to gehenna Z3, more or less

- _std/__build.dm
- code/datums/controllers/process/kudzu.dm
- code/datums/mutantraces.dm
- code/modules/_unused/kudzumen.dm
- code/modules/admin/admin.dm
- code/modules/events/gimmick/kudzu.dm
- code/modules/interface/multiContext/context_actions.dm
- code/obj/critter/plants.dm
- code/obj/item/seeds.dm
- code/obj/machinery/computer/cloning.dm
- code/obj/machinery/plantpot.dm
- code/obj/submachine/seed.dm
- code/procs/fireflash.dm
- code/procs/mobprocs/chatprocs.dm
- coolstation.dme
removes kudzumen and repurposes the bulbous coccoon things. now they'll just gib the body that died in it after a while, (or still dose it with poison if you break it open) but thats it, no kudzumen. just gibs.
This uh, "antag?", while actually super fuckin interesting and very cool to look at, and also wild thematically, has been a source of major confusion with regards to selfantagging, and rather blurs the lines between a *wink-wink* "punishment" and a straight up dying reward. 
Hopefully this will be revisited someday, or the mob recycled as a pure random antagonist (or a traitor item, grow-a-man botanist kit? sure!)
but for now its a balancing nighmare and we could do with reduced scope. 
Into the bin! 
```changelog
(u)warc
(*)removed kudzumen. kudzu pods now gib bodies, so you'd do …
```
> kudzoolander

- code/datums/controllers/sea_hotspot_controls.dm
- code/modules/worldgen/GenerateMining.dm
- code/obj/item/device/pda2/base_os.dm
- code/turf/floors.dm
[feat]
Makes gehenna have a mining map for the desert bit and also for the space bit.
(I think the red dots inside the gehenna blob are the elevators. Probably nice to have those represented? but maybe not as unknown bits.)
Hell yeah
```changelog
(u)BatElite
(+)Gehenna gets two mining maps now.
```
> Mining map support for gehenna Z3

- _std/macros/dir.dm
- code/modules/atmospherics/atmos_crafting.dm
- code/modules/atmospherics/machinery/unary/freezer.dm
- code/modules/power/TEG.dm
- code/obj/item/building_materials.dm
[bug]
-Pipe frame base type is now abstract, exchanger pipes are a subtype because having base types not be generic is asking for trouble
-Fixes a bug that accidentally allowed pipe frames to stack with anything. That included worn clothing and internal organs, so doing this turned out surprisingly lethal
-Splitting up regular pipe frames was also broken, because I didn't actually test the item stacking shit the first time around :3
-Welding or adding a module to a stack of pipe frames only does one at a time instead of the entire stack
-Cold sink module removed from vendor, but freezer (a kind of cold sink) is now mechscannable
-Heat reservoir module replaced with furnace connector module. Furnace was already mechscannable. (freezer units are direct unary atmos but furnaces aren't??) …
> Fixes for buildable atmos 1

- code/datums/jobs.dm
- code/modules/admin/admin_verbs.dm
- code/modules/fishing/fishing_gear.dm
- code/modules/fishing/fishing_spots.dm
- code/modules/vending/vending.dm
- code/obj/machinery/deep_fryer.dm
This adds many more acceptable fishing points for use with the fishing rod.
It also adds 3 regular fishing rods to the botany GardenGear vendor.
Ranchers now spawn with an improved bamboo pole that will catch fish roughly twice as quickly as a regular rod.
Added an admin verb for a fishing event
Prevents you from frying a fishing rod. While hilarious, the bamboo rods *are* a limited resource.
Fishing made better
```changelog
(u)Camryn
(*)Fishing revamp, open for details
(+)Ranchers spawn with an extra fast fishing rod
(+)You can find regular rods in the GardenGear
(+)You can fish from a lot of different objects and locations now, some more sane than others.
```
> fish revamp

- code/modules/atmospherics/FEA_group_helpers.dm
Fixes `find_groups` to use `|=` instead of `+=` for `tiles_to_update` (which prevents adding the same turf multiple times and is also how that's added to everywhere else)
New turfs would each call that proc, which meant that after a large explosion every replaced turf would add duplicates of entire airgroups to the update list over and over.
Those are all 7k explosions spawned in the gehenna burn chamber. No wonder it'd die :P
At least on local this makes huge explosions on lower gehenna not hang atmos permanently, although those do make huge airgroups that never seem to settle so it's still not exactly smooth sailing.
The next bottleneck for explosions seems to be all the new turfs copying materials. I think Zewaka optimised that on goon, so if I can find that we could port it.
> this fucking FEA helper

- code/turf/floors.dm
- code/turf/turf.dm
Moves a thing out of ReplaceWith to save a typecheck,  and comments out a proc that is itself entirely commented out.
I'd throw this at master directly but IDK if skipping a typecheck outweighs simmed floors having to call the parent BUT ALSO I need to go _the fuck_ to bed. I'm letting someone else judge if it's actually good while I cease being awake.
I trust the empty RL_Cleanup already gets stripped out on compile but now it's explicit
proc needs to go fast to time for bullshit
> Maybe a small ReplaceWith optimisation?

- maps/warwip/gehenna_colony.dmm
- maps/warwip/z3_gehenna.dmm
188, 082, station zlevel.
202, 082, z3.
This was mostly so I could practice mapping, but I do think the desert needs a bit more pizzaz. The Middle of Nowhere is a location for crime staging for when you want to have a couple dozen tiles of burning desert between you and sec, or a place to escape to and relax if the station's getting destroyed. It also connects to the underground for mining shenanigans.
```changelog
(u)Krowmeat
(*)Added an abandoned house in the Gehennan desert.
```
> Middle of Nowhere, for chilling out or criming

- maps/warwip/z3_gehenna.dmm
Adds a crashed ghostdrone factory to Gehenna, east of Mining. The factory loads drones onto a conveyor belt and has a disposal chute that leads into a storage closet nearby.
Ghostdrones needed.
```changelog
(u)Krowmeat
(*)Added an underground ghostdrone factory to gehenna.
```
> Ghostfactory

- _std/defines/chemistry.dm
- code/modules/chemistry/Chemistry-Holder.dm
- code/modules/chemistry/Chemistry-Tools.dm
- code/modules/chemistry/tools/beakers.dm
- code/modules/chemistry/tools/bottles.dm
- code/modules/chemistry/tools/food_and_drink.dm
- code/modules/chemistry/tools/fuel_tanks.dm
- code/obj/item/hydroponics.dm
- code/obj/submachine/robotics.dm
- code/procs/gamehelpers.dm
Adds an RC flag to add the (approximate) reagent amount in the inventory counter, if used.Needs RC_SCALE or RC_FULLNESS to do anything. I've kinda cobbled this together and it's not thoroughly tested.
Added flag to beakers, fuel tanks, the chem bottle parent and whatever else felt correct.
There's a second, commented out flag for how many units you pour out. It didn't quite work as I wanted (probably needs to be on reagent_containers/glass to work) and also for space reasons. As you can see a triple digit volume already runs past the sprite's width, so adding more would get ugly.
Aside from our tooltips being unreliable at the moment (who knows why), this just seems like a nice bit of QOL
(With RC_SCALE and RC_FULLNESS respectively)
```changelog
(u)BatElite
(+)There's now nice volume …
```
> reagent holder volume counter thing

- code/modules/food_and_drink/sandwiches.dm
- code/modules/medical/pathology/pathogen_symptoms.dm
- code/modules/status_system/statusEffects.dm
Adds a new status effect that can spawn hallucinated objects just out of view of the affected mob. The status effect is hidden.
The hallucinated objects can be one object or a list.
The hallucinated_item code was already in pathogen_symptoms.dm
For testing, there are "temptation" subtypes of burgers and sloppy joes now that will give the status.
Should probably be fixed before merging:
- The "owner" var is not passed properly to the hallucinated_item and I don't know why, so the item can't be interacted with. I'm not sure why it checks for the owner var before interacting in the first place since only the owner can see it.
- The items never disappear, I'm thinking maybe they can just disappear after 30 seconds so they don't need to be tracked in a big list
- I _think_ the …
> Status hallucination system part 1? (WIP)

- maps/warwip/gehenna_colony.dmm
Expands the middle of nowhere bedroom to act more like a fully-fledged radio station and changes the area designation to a not airless one
The middle of nowhere was originally intended to be a radio station, and since I fucked up the area and made it airless I figured it's a good opportunity to make it That, Officially
```changelog
(u)Krowmeat
(*)The house in the middle of nowhere now has a full pirate radio setup!
```
> Adds air back to the Middle of Nowhere and turns it into more of a radio station

- code/mob/melee_attack_procs.dm
- code/obj/furniture/chair.dm
- Move the check for `climbable` on `/obj/stool/chair` from `MouseDrop_T` to the `buckle_in` proc 
- Change behavior of using resist hotkey on a tile with a chair to respect intent wrt deciding whether to buckle in or climb up
Parity between using click drag and resist hotkey for interacting with chairs
> Make hotkey chair buckling respect intent

- code/obj/machinery/microwave.dm
Stick some `return`s after `attackby` branches related to fixing/cleaning the microwave
Currently you simultaneously start fixing/cleaning the microwave and then shove the item you're using into the broken/dirty microwave (and if you interrupt the action bar you just can't get the item back cuz the interface doesn't have an eject button when it's broken)
> Add returns to microwave attackby

- code/datums/preferences.dm
- code/datums/pronouns.dm
- code/datums/savefile.dm
- code/mob.dm
- code/procs/mob_procs.dm
- Change `get_pronouns` proc to use they/them as fallback instead of using gender variable (like how e.g. `he_or_she` does)
- Condense procs like `he_or_she` by using `get_pronouns`
- New type `/datum/pronouns/custom` that has fields set by `create_pronouns` global proc
- Add savefile fields for custom pronoun information 
- Change character customization menu to show list of pronouns instead of cycling through them on click
- Add option for custom pronouns to the latter
Only issue right now is the prompts when you're creating custom pronouns are kind of confusing (who the fuck knows what objective/subjective/reflexive is) but I tried to mitigate that by making it autofill the answers to whatever the values for the currently selected pronouns are so you have an example for that field. …
> Custom pronouns

- _std/macros/procs.dm
- code/mob/living/critter/ai.dm
- code/modules/atmospherics/portable/canister.dm
- code/modules/chemistry/Reagents-PoisonEtc.dm
- code/turf/floors.dm
[BUG]
Attempts to fix some load bearing switch failures by putting blank conditions for some. and also removing some switch cases which aren't used.
I mean, you could live without it. but i hate having notification popups. i like all the numbers to be 0. Should prevent the 5 warnings that pop up.
> try and fix some switch cases

- code/obj/item/material.dm
Moves the location of the `glass stepping crunch sound` line so that it plays even if the person isn't being hurt (is wearing shoes, or is a cow, or has robot legs, etc).
Doesn't make sense for it to be totally silent. It's still a glass shard, just because I'm wearing shoes shouldn't silence it.
> Glass crunches underfoot more

- code/mob/dead/ai-camera.dm
- code/mob/living.dm
- code/modules/interface/action_associations.dm
- code/modules/interface/keybind_style.dm
- code/procs/mobprocs/chatprocs.dm
Ported from this goonstation PR by pali: https://github.com/goonstation/goonstation/pull/6423
In pali's words:
This PR adds a new keybinding ; which lets you say stuff over your "main" radio channel (it just asks for input and then says what you entered with a ";" prefix as if you used T and then typed in ; first).
It's annoying to have to hit Y every single time, or T+;. Now you skip a keypress. Handy!
```changelog
(u)Tyrant
(*)You can now press ; directly to talk over the main radio channel.
```
> Semicolon for main radio (ported from goonstation #6423)

- code/datums/manufacturing.dm
- code/obj/machinery/manufacturer.dm
Adds pride bedsheets (but not normal bedsheets) to the uniform manufacturers.
Also cleans the code a bit by making the uniform fab list a define. A hassle but it's futureproofing and code quality.
It's good to be able to get the pride bedsheets in game.
```changelog
(u)Tyrant
(+)Pride Bedsheets are now available in the uniform fabricator.
```
> Add Pride Bedsheets to the uniform manufacturers

- code/datums/components/mechComp_signals.dm
If the access panel is open on a vending machine or door, prevent the mechcomp connections window from popping up.
Airlock popup prevention ported from TTerc's PR at https://github.com/goonstation/goonstation/pull/5844
Vending machine popup prevention ported from TTerc's PR at https://github.com/goonstation/goonstation/pull/6506
It's annoying to have to click away the window when hacking something. If they want the window, they probably won't open the access panel.
> Prevent Mechcomp on open access panels (ported from goonstation #5844 and #6506)

- code/modules/gunse/modular_ammo.dm
Change `.` to `?.`
When you're reloading a gun with an ammo box and it runs out it starts getting qdel'd but `update_stack_appearance` still runs before its gone and theres no inventory counter anymore so it runtimes
> Fix runtime when reloading gun's

- code/datums/emotes/emote_mutantraces.dm
- code/datums/emotes/emote_parent.dm
- code/datums/mutantraces.dm
- code/mob.dm
- code/mob/living.dm
- code/mob/living/carbon/human/procs/emote.dm
- code/procs/mobprocs/chatprocs.dm
- code/world.dm
- coolstation.dme
-The main important thing about this PR is it moves the main emote execution code from `/mob/living/carbon/human` to `/mob`. The remaining human emote code just finds the appropriate datum, looking for a mutanrace override first and human emotes after thatn. (it also needs some cleanup, but later)
-Replaces the emote controller with `get_singleton`, a proc I didn't know about at the time I wrote the controller.
-Sloppily ports almost all the existing mutantrace emotes over to datums. The result is inconsistent in inheritance and jank otherwise, but from what I've tested it works. Definitely needs more love though.
-Removes monkey overrides for whimper and yawn, because they were basically identical to the regular versions except for a muzzle check.
As a sidenote, I'm really hating a bunch …
> emote datumisation part 2: mutantraces

- code/obj/item/device/scanners.dm
[sprites][bug]
fixes the atmos analyzer inhand disappaering when you put an upgrade module in it
silly analyzer goes invisible when you put an upgrade in it, which is silly, and annoying, because i like holding my atmos analyzer so everyone can look at me and be like "yeah that guy is holding 3-5 pixels of Something in his hand"
> Fix atmos analyzer inhand disappearing when upgraded

- code/datums/mutantraces.dm
Lizards no longer say SSSSSShit, instead say Ssssshit.
SHIT -> SSSSSSHIT
Shit -> Sssssshit
shit -> ssssssshit
The same applies to cows and amphibians.
The lack of proper capitalization for mutant race speech annoyed me, and this system is easily expandable. 
```changelog
(u)klushy225
(+)Fixed mutantrace stutter
```
> Fixes mutantrace stutter

- code/modules/economy/shippingmarket.dm
Applies a bandaid fix for artifact research restocking. There are probably still issues with the restocking being triggered while the shuttle is docked at the station.
Bugfix
```changelog
(u)Camryn
(+)You should now actually be able to restock artifacts by selling fully researched and labeled ones at QM
```
> bandaid for artifact restock

- code/client.dm
- code/datums/gameticker.dm
Rearranges a bunch of client/New() so that option that are set in the title bar will get fetched from the cloud. The previous methods of fetching these are still around in case there's no cdn (so, locally).
The following are saved when they are toggled:
-FPS
-widescreen/square view
-vertical/horizontal split
-dark mode
-depth shadowing
-view tint
-tg HUD layout
-tg controls
-use CHUI
-use CHUI's custom window frames
-Item ghosts on hover
The following are toggled directly via a winset(), and so there wasn't a verb for me to hook a save onto. They're instead saved when the ticker loops over all clients at the end of the round:
-icon sizing
-stretch mode
-fullscreen
-hide status bar
-hide menu
I have no clue how I could conceivably test this working properly on local, beyond building and …
> Save more settings to the dang cloud thanks

- code/WorkInProgress/recycling/disposal_chute.dm
- code/WorkInProgress/recycling/mail_chute.dm
- tgui/packages/tgui/interfaces/DisposalChute/index.tsx
- tgui/packages/tgui/interfaces/DisposalChute/type.ts
- Fix the mail chute UI bluescreening when the mail chute is in a weird mode (specifically, `DISPOSAL_CHUTE_NOTRUNK` or `DISPOSAL_CHUTE_NOTAG`).
- Make mail chutes re-check their trunk and tag status when their power is toggled on.
- This does mean that untagged chutes can't be flushed anymore
- Disable "Flush" button when the chute has no trunk or tag
UI bluescreens bad, mail chute go wheeeeee
```changelog
(u)offbeatwitch
(+)Fix the mail chute UI bluescreening on missing trunk or tag
```
> Fix mail chute UI crashing on weird modes

- code/datums/gameticker.dm
tldr; game does not start if there are no clients in lobby
unless I_DONT_WANNA_WAIT_FOR_THIS_PREGAME_SHIT_JUST_GO is defined
joining a round that has been empty for 40 minutes and everything is fucked up sucks
```changelog
(u)jimmyl
(+)game does not start if there are no clients in lobby
```
> prevent the pregame timer from ticking down if there are no clients

- maps/klushywip/bayoubend.dmm
connects all printers to network on bayou bend and makes wall phones and air alarms only accessible from inside the room
i had to move certain air alarms and move duplicates
printers werent connected to network so they were functionally useless
wall phones such as in logistics could be interacted with from the adjacent rooms (and also air alarms while i was at it)
makes those things not true
```changelog
(u)jimmyl
(+)connects all printers to network on bayou bend and makes wall phones and air alarms only accessible from inside the room
```
> connects all printers to network on bayou bend and makes wall phones and air alarms only accessible from inside the room

- code/WorkInProgress/MechanicsNetworkCon.dm
Applies the same fix from https://github.com/goonstation/goonstation/pull/3254 on wifi to powernet, special characters will be %xx encoded, which the signal splitter can actually split
Signals with special characters in them are impossible to parse with the signal splitter currently, it will now split the most complex of signals correctly
```changelog
(u)patricia
(+)The signal splitter component can now correctly parse powernet packets with special characters
```
> Fix powernet mechanic component mangling packets

- code/obj/item/device/gps.dm
Outputs x and y as their own signals on GPS units and tracking implants
Signals in weird formats are hard to parse this just standardizes it so that components like the signal splitter and the dispatch module and whatnot can access this data
```changelog
(u)patricia
(+)GPS coordinates in packets are now in x=, y= format compatible with signal splitters
```
> Output GPS coords in signal list format

- code/mob/input.dm
- code/modules/interface/mob_input.dm
you cant click distant objects to rotate if youre dead or unconscious
same with pressing movement keys
wanted to extend it to stuns but idk if that would be good
it looks dumb
```changelog
(u)jimmyl
(+)you may no longer roll while unconscious or dead
```
> you may no longer roll in the grave while unconscious or dead

- _std/macros/mob_properties.dm
- code/WorkInProgress/ObjectProperties.dm
- code/datums/movement_modifier/movement_modifiers.dm
- code/mob/living.dm
- code/mob/living/carbon/human.dm
- code/mob/living/life/stuns_lying.dm
- code/modules/status_system/statusEffects.dm
- code/obj/item/clothing/shoes.dm
[enhancement]
This PR adds slidekicking (back sorta)! To slidekick, throw nothing, and you will flop over and slam your feet into up to two items on the floor in that tile! You can also deal a lil bit of damage (1 or 2, without some source of epic footwear buffs) to a person on that tile, and punt Beepsky like a dumb little football (he hates this).
You can kick items and they are treated as thrown a short distance (dependent on weight).
Slidekicking stuns ("weakened" status) you for 0.4 seconds + 0.1 seconds per tile, or twice your movement delay- whichever is higher- so its not generally gonna help you get around faster.
The distance you slidekick is affected by a MOB_PROPERTY, called PROP_SLIDEKICK_BONUS. It starts at 1.
If you need to slidekick in an epic fashion, you have the …
> Basic slidekicks and epic slidekicks

- code/mob/living/carbon/human.dm
[bug]
I messed up the indentation and accidentally made slidekickings "make sure they arent handcuffed or stunned" check not stop the execution of the slidekick. This indents the affected block to be inside the check, and adds early returns for legibility.
Cuffed or stunned fools should NOT slidekick.
> Fixes being able to slidekick when you shouldn't

- code/obj/item/device/pda2/cartridges.dm
Adds the maintenance arrears pda program to cyborg and AI pdas.
So engineering borgs and ai shells can help repair the station.
```changelog
(u)Camryn
(+)Added the maintenance arrears program to cyborg and AI pdas.
```
> Adds maintenance arrears program to cyborg and AI pdas

- browserassets/css/browserOutput.css
- browserassets/js/browserOutput.js
- code/client.dm
- interface/skin.dmf
Replaces the dark mode theme with a very cool theme, yellows browns and beige.
Maintained a similar contrast ratio for ease of creation and because players like dark themes- the window chrome is a compromise because you can only use black white or shades of grey due to a bug
Goon's dark theme is not cool- the bluish modern tones are totally out of place ~~and completely tacky~~
Helps give cool a stronger visual identity
```changelog
(u)patricia
(*)Replaced the dark theme with a very cool theme! Report any contrast issues you find!
```
> Replaces the dark mode theme with a very cool theme

- code/procs/helpers.dm
Double semicolons don't eat what you were trying to say
Papercut bug with general radio key
> Double semilcolons talks on general channel

- code/modules/admin/admin_verbs.dm
- code/modules/interface/action_associations.dm
- code/modules/interface/skin_input_box.dm
- interface/skin.dmf
Admin and mentor and player OOC boxes match their chat color, stealth mode even swaps them.
Style fun and good UX
> ooc and looc inputs are skinned; custom colors for admins and mentors

- code/datums/supply_packs.dm
- code/modules/power/TEG.dm
thermoelctric -> thermoel**e**ctric
Also tiny adjustments to the cargo item text to standardise it with the rest
typo fixo
> Fix furnace crate typo

- _std/defines/component_defines.dm
- code/obj/item/mousetrap.dm
- code/turf/floors.dm
- code/turf/turf_persistent.dm
[Goonstation PR #17915](https://github.com/goonstation/goonstation/pull/17915)
Allows you to hide tiny items under floor tiles, and makes mousetraps trigger when revealed this way
Fun way to hide items and set funny traps
```changelog
(u)LeahTheTech [upstream]
(*)Tiny items can now be hidden under floor tiles, mousetraps hidden like this will trigger when the tile is pried up again.
```
> add hiding items under floortiles

- code/modules/power/apc.dm
- code/modules/power/cell.dm
- code/modules/power/furnace.dm
- code/obj/machinery/glass_recycler.dm
- code/obj/machinery/manufacturer.dm
- code/world.dm
two new map flags - NO_EASY_BEAKERS and POWER_IS_CRAPPY
scarce beakers flag is for maps where large chemical storage such as beakers are pre-placed, and new ones can't be made.
crappy power flag is for maps where you want power generation and storage to be more of a struggle
```changelog
(u)Arborinus
(*)Two new map flags related to map scarcity, rely on the mapper's sick design skills!
(+) NO_EASY_BEAKERS - makes certain big chem containers not producible
(+) POWER_IS_CRAPPY - power generation + storage is much worse
```
> 2 map flags related to scarcity

- code/datums/jobs.dm
- code/mob/new_player.dm
Fixed the chui version of the latejoin screen and made it the only version because it is not structured well to support two themes well- the chui version has no issues like some things and is only shown when joining the round
Tryin to make da game look good
> Fix latejoin chui theme and chuify it

- code/modules/chemistry/tools/dispensers.dm
This adds a six second action bar to stuff a corpse into a compost bin, getting rid of that nasty ol' evidence. It makes a pretty audible splat when it falls in, though, and gets blood in your compost bin.
Most departments have a way to say goodbye to a corpse... why not botany?
```changelog
(u)Mylie
(*)You can now compost corpses. In fact, I encourage it.
> Compost some corpses today!

- code/modules/chemistry/Chemistry-Recipes.dm
- code/modules/chemistry/Reagents-PoisonEtc.dm
A altered semi-port of something i made for upstream (neurodepressant over there), made by isolating it from the regular neurotoxin. It acts much like neurotoxin, but doesn't directly damage or KO you, instead causing increasing misstep and assorted dizzyness effects.
It's a fun chem that doesn't just drop you dead or KO you. Has it's uses both as a prank and more nefarious chem. Can be useful to gain an advantage in combat or just mess with people.
```changelog
(u)Colossus
(*) Added a new chem, vertigo!
(+) Vertigo can be made by heating acetone (1), neurotoxin (2), and sulfuric acid (1) to very high temperatures. It acts much akin to neurotoxin, but without the damage or KO. Still, the sheer misstep and assorted dizziness effects can be quite debilitating.
```
> Adds Vertigo compound, a drug that messes with muscle coordination

- code/datums/jobs.dm
- code/mob/new_player.dm
Updates latejoin job colors to match more closely to the current colors in chat and match the default chui theme
The colors are old and it's a little hard to look at at the moment
> Further refine latejoin screen

- code/modules/chemistry/tools/syringes.dm
As the title suggests. If you're on harm intent, you can stab someone with a syringe to quickly transfer 5 units of chemicals into them, dealing 5 brute and making a loud stab sound. This is much more conspiquous than just stealthily injecting someone, and it causes you to drop the syringe, whether you got chems in or not.
https://github.com/user-attachments/assets/9c89b79c-8179-4829-9d1a-6a03838f4754
A fun way of attacking people. Whether you actually want to kill someone, or are just running around like a madman poking people with ketchup.
```changelog
(u)Colossusqw
(+)Injecting chems into people via syringe on harm intent now causes you to jab them with it. It deals some brute, makes you drop the syringe, and causes a loud noise, but is faster than regular injecting.
```
> Jab people with syringes

- code/client.dm
- code/datums/jobs.dm
- code/mob/new_player.dm
Bigger window because the collapse happens at different sizes when the server is live (why).
Also command is green
Meep meep
> Latejoin window is yet bigger

- browserassets/css/chui/themes/default/default.css
- browserassets/js/jquery.nanoscroller.min.js
- code/mob/new_player.dm
Margins are now adjusted for whether the scrollbar is visible or not. This was done by modifying our (abandoned) scrollbar library to set a css class when the scrollbar is visible. Additionally, the latejoin screen has been updated to use flex margins to center it and proportional margins and calc() so that the tables do not collapse if the screen is slightly too small.
I've also unminified the script because I believe grunt will minify it before uploading to the CDN- to be seen.
Fixes layout issues across various chui applications and for the first time makes the margins correct even if the scrollbar is not always visible.
> Smart scroll bar margins for chui

- code/chui/window.dm
- code/obj/machinery/computer/QM_supply.dm
Forces QM computer into html mode even if user prefers chui
Chui QM console is unmaintained, half assed, and broken in multiple ways.
```changelog
(u)patricia
(+)QM console no longer supports "chui style popups"- which you should try btw!
```
> Disable chui for QM computer

- code/obj/item/grab.dm
This PR increases the volume available on rags, and the speed at which chemicals are transfer, as well as only needing an aggressive grab to start transfering, but removes the INGEST effect from the transfer.
Right now rags don't really serve the function of stealthy way to knock someone out, instead, being something you never use outside of quickly permastunning and killing someone on a neck chokehold via spamming the bath salts ingest effect. These changes should hopefully make it more useful in it's inteded role, and less awkward with the instastuns.
```changelog
(u)Colossus
(*) Cloth Rag chokeholds have been significantly altered. More in minor changes.
(+) Cloth Rag chokeholds start transfering chems on aggressive grabs, can transfer more and faster.
(+) Cloth Rag chokeholds no …
```
> Changes the behavior of cloth rag chokes

- _std/macros/mob_properties.dm
- code/datums/manufacturing.dm
- code/mob/living/carbon/human.dm
- code/mob/living/carbon/human/machoman.dm
- code/modules/chemistry/tools/food_and_drink.dm
- code/modules/chemistry/tools/fuel_tanks.dm
- code/obj.dm
- code/obj/item/clothing/gloves.dm
- code/obj/item/clothing/shoes.dm
- code/obj/item/lifting_wrapper.dm
- code/obj/machinery/espresso.dm
- code/obj/machinery/glass_recycler.dm
- code/obj/machinery/microwave.dm
- code/obj/submachine/cooking.dm
Fixes and updates the lifting wrapper. Now you can throw microwaves and shit again! Also, other people can't force microwaves into your hands instantly and make you drop everything you're holding! Throwing a wrapped object now just throws the object, allowing the object to use it's own throw_impact and such procs and throwforce etc variables.
Also, I added a debug option for this - PROP_LIFT_ANYTHING.
The powerlifter gloves (unobtainable) and being a macho man (already gamebreaking) apply this property to you, letting you pick up 99% of objects (I didn't feel like fixing every vendor-like that overwrites and doesn't call parent on MouseDrop).
Use these gloves to figure out what sorta stuff feels fun to throw around.
There were some issues with the wrapper especially with throwing the …
> Chucking appliances

- code/modules/chemistry/Reagents-Medical.dm
- code/modules/medical/diseases/malady.dm
This PR significantly changes both ether and morphine, with the intent to make them quite different from eachother. Morphine has had it's depletion halved, but does not KO easily, taking either an OD or a significant time to get there. This makes it much more useful as a low dosage 'shrug off damage' chem, but not as useful as a just KO one. It's depletion also returns to 0.4 when it's KOing you, and you run the risk of the more dangerous OD effects.
Ether, on the other hand, is now much faster, being 4 cycles faster than a capu KO, but having a bigger 0.6 depletion to boot. OD dosages will also deplete much faster, so KOing someone for a long period isn't very feasible.
Ether and Morphine are incredibly similar right now, and these changes should hopefully place each in their respective …
> Differentiates functioning of Ether and Morphine

- code/WorkInProgress/AnimationLibrary.dm
- code/turf/walls.dm
Oops! The big ferns thing made interact_particle center itself on bigger sprites, but I forgot that turfs don't have the required variable for that calculation.
Runtimes bad.
> Fix a runtime I introduced with interact_particle on walls

- code/mob/living/life/disability.dm
- code/modules/chemistry/Reagents-Medical.dm
For some reason drowsiness KO time was being called twice, since it called both the var to set you asleep and a 5 second KO. Now it's only the 5 second KO, which it removes from the total drowsiness counter. It's overall much less annoying. Ether changed to feel less sudden, with lower early drowsiness but a bit more consistent, and less late drowsiness. Should overall have a lot less of randomly getting you down long after it's left you.
Stops it from randomly making you fall asleep long after there aren't any chems left to keep you passing out.
> Drowsiness doesn't KO you for 10 whole seconds

- _std/defines/atom.dm
- code/WorkInProgress/AnimationLibrary.dm
- code/atom.dm
- code/datums/components/pitfall.dm
- code/datums/controllers/throwing_controls.dm
- code/modules/status_system/statusEffects.dm
- code/obj/item/grab.dm
- code/obj/item/tank.dm
An absolute mess of work was required for this, but here we go. Throwing something into a pitfall now lets it sail into adjacent pitfalls while animating the falling. Also, jetpacks work on pitfalls a bit better, and some misc refactoring to thrown stuff and to jetpacks was done to support these changes.
https://github.com/user-attachments/assets/a43cce55-cf15-4af5-b148-7c912b80e9ae
Bob wanted thrown stuff to sail into pits, not drop in one spot!
> Throwing things into pitfalls is cooler

- code/mob/living/carbon/human.dm
Adds an early return for mindless mobs to bypass checking logic, since mindless mobs won't have objectives, be insurgents, and don't need to earn medals.
Fixes a pre-roundstart runtime caused by corpse bodybags being checked for objective completion.
> Mobs that die with no mind are no longer checked for objectives/medals etc.

- browserassets/css/chui/themes/default/default.css
It went to the beach that makes the :focus-visible old
> PR that makes the active hilight old

- code/datums/titlecard.dm
Join text was hella blurry
Literally unreadable (literally)
> Fix the text stroke on the join screen

- browserassets/css/chui/themes/default/default.css
All the native scrollbars now use native webkit custom scrollbars which are 1:1 the same as the nano scrollbars
Consistency! Also I'm gonna remove nano scrollbars!
> Native custom scrollbar css

- code/datums/jobs.dm
Most ofof the the job colors have been re-selected within accessible contrast ratios, there were some creative limitations with this especially with the hue shift for command and logistics but this was the range that was available
Make the game visually pleasant and accessible
> Adjust the job colors to meet contrast standards

- browserassets/css/chui/themes/default/default.css
- code/chui/theme.dm
- code/mob/new_player.dm
Nano scrollbars have been replaced with native wekit custom scrollbars, thank you Webview2!
Margins were also shrunk by 5px I've checked every known chui/pcui interface for consistency with this change
We don't need to implement scrollbars ourselves anymore and I was having trouble working with that library!
> Native scrollbars and minor margin tweak

- code/chui/pcui/templates/selector-template.dm
Sets the name instead of setting an unnamed tag
> spawn windows don't share the same name

- code/obj/airbridge.dm
- code/obj/machinery/door/door_parent.dm
- code/turf/turf_drawbridge.dm
`/obj/airbridge_controller` has a new `auto_pressurize` var, I set it default true, it will pressurize the airbridge after it's established which was previously only done if someone manually pressed the button??
There's also some new airbridge_controller subtypes with classic turf appearances. Wowie! Remember to set both sides to the same subtype.
<br/>
`/obj/machinery/computer/airbr` has two new vars that mappers can change:
- `bolt_doors` : set true for ALL computers for an ID. This will force close and bolt all doors with the same ID as the computer when the airbridge is retracted, and vice versa.
- `auto_retract` : set true for ONE computer for an ID. This will cause the airbridge to retract after the `auto_retract_time`
```changelog
(u)Arborinus
(+)Mappers can now place airbridges …
```
> Auto closing airbridges - New old airbridge appearances

- code/modules/food_and_drink/ingredients.dm
- code/modules/food_and_drink/pizza.dm
Pizza dough now accepts W_CLASS_NORMAL [3] items as toppings, and has a larger pool of topping space (20 w_class instead of 10).
Pizza dough is now W_CLASS_BULKY [4], up from W_CLASS_NORMAL [3]. The cooked pizza is less floppy and easier to carry, remaining at W_CLASS_NORMAL [3] (meta reason: because you cannot remove the toppings from it).
Basically, you can't put pizza dough in your backpack, but it holds items that can fit in your backpack but not belt now.
As an easter egg, a way to make BUBSIAN pizza dough has been added. This pizza accepts ANY size of topping, and as many as you can cram onto it without running out of clickable space.
It's frustrating to try and put funny things on a pizza and realize they aren't small!
```changelog
(u)Mylie
(+)Embiggened the pizza dough.
```
> bigger pizzas for bigger toppings

- code/WorkInProgress/gehenna.dm
Makes the beaten paths on Gehenna use their old, pre-overlay icon state in mapping software.
Mappers couldn't see the beaten paths.
> Makes Gehennan paths visible in StrongDMM again

- maps/warwip/z3_the_crag.dmm
Removes airless tiles from the crag's lower level, which were accidentally added in the refresh.
> Remove non-engine airless tiles from crag z3

- code/WorkInProgress/gehenna.dm
- code/modules/atmospherics/FEA_system.dm
- code/modules/atmospherics/FEA_turf_tile.dm
FEA airgroup spacing could space an airgroup if it touched any subtype of /turf/space, including planetary surfaces. For the /turf/space/fluid type, it was doing a second istype check to make sure it didn't hit that.
This replaces both checks with a single istype_exact() check in two places, and makes sure Gehenna's sand doesn't get selected as the space sample.
Gehenna was ending up with spaced rooms despite having an atmosphere outside, and spaced prefabs in the asteroid field would sometimes become breathable if the map loaded was Gehenna.
> Alters FEA spacing to check for ACTUAL space.

- code/atom.dm
- code/datums/gameticker.dm
- code/modules/fluids/fluid_turf.dm
- code/modules/worldgen/worldgen_parent.dm
- code/obj/grille.dm
- code/obj/mining.dm
- code/obj/window.dm
- code/turf/turf.dm
- code/turf/turf_autoalign.dm
- code/z_dmm_suite/reader.dm
Expands the little system we had for batching all the turf sprite updates so that anything can subscribe to it and so it allows for an amount of recursion (wingrilles spawning windows need this). This means that when doing map loading (both initial, but also generating asteroids or placing prefabs) we can batch handle things that require having spawned in the whole map. A lot of the time this is for graphical updates (windows, walls etc), but the cloner could also benefit.
Chunk, spawn counts above 250:
Seems to work fine as it is. as you can see up above there's a bunch more stuff that we ought to move over to this system. I think the window code is a bit inefficient in that they all start messing with air groups, but that's for later.
I'm not sure how this affects performance overall, …
> system for deferred world gen (that isn't spawn_dbg)

- maps/warwip/the_crag.dmm
Accidental airless tiles added to the fossie outpost were removed, and tiles in the engine exhaust were made airless. Chances are they got caught in a regex find and replace.
Fossies (debatably) deserve to breathe, and this should make the engine on crag a little more consistent.
> Removes some airless tiles from the fossie outpost, adds some airless tiles to the engine exhaust

- code/procs/fireflash.dm
Tiny change to enable a fireflash's temperature affecting the present atmos.
Burning fuel in the burn chamber should do something.
```changelog
(u)Mylie
(*)Chemical combustion now heats air, so uh... engine??
```
> Fireflashes from combustion heat air

- code/obj/item/clothing/masks.dm
Also fixed a typo, kinda subjective but I didn't really like it and couldn't come up with a better typo
The colored masks turned into default mask
#546
> fix colored clown masks turn into normal clown mask

- code/modules/fishing/fish.dm
This PR makes it so even if you don't have kitchen training, you still remove the liver from the pufferfish and have about a 70% chance of making a non-poisonous one.
It's more fun like this, makes it harder to know if that fish meal is poisoned or not, and gives dubious pufferfish meals an element of luck, that not even the person who prepared it can know if they got it right.
```changelog
(u)Colossus
(+) Badly made pufferfish now also drops the liver, and has a chance of not being poisonous.
```
> Fugu shenanigans

- code/area.dm
- code/global.dm
- code/obj/machinery/door/airlock.dm
As it's configured right now, airlocks that look the same will share wire distributions. For example: any non-perspective external airlock shares wires regardless of access requirements, but they don't share with perspective external airlocks. I remember there being a good deal of disagreement about how to group doors, which is why that is isolated to its own proc. I've got an opinion, but mostly I wanted to get moving on the functionality already.
Makes it potentially more difficult for folks to hack into places, since the bridge doors may not necessarily be hacked the same way as some random door in Butte-Aess, Maintenance that nobody will notice you testing on.
```changelog
(u)BatElite
(*)To make hacking a bit more difficult, airlock wiring is now grouped per type of door.
```
> Airlock wire groups

- code/modules/admin/admin_verbs.dm
- code/modules/admin/randomverbs.dm
- strings/admin_changelog.txt
Adds a new verb that lets an admin blindfold, earmuff, or muzzle all players, dropping whatever the player was wearing in said slots on the ground. There is an option to make these items irremovable.
Funny way to fuck with people.
> Adds a new 'No Evil' admin verb

- code/modules/chemistry/Chemistry-Holder.dm
- code/modules/chemistry/Chemistry-Reagents.dm
- code/modules/chemistry/Reagents-Misc.dm
- code/procs/gamehelpers.dm
Adds a weight to reagent containers color calculation (simple version instead of #612)
Allows to conceal harmful reagents' colors
> Beaker dyes simple
